spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        type: trace
  h2:
    console:
      enabled: true
